CREATE DATABASE IF NOT EXISTS helpinghands;

CREATE TABLE IF NOT EXISTS "users"(
    "id" SERIAL PRIMARY KEY NOT NULL,
    "name" VARCHAR(40) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "role" VARCHAR(255) NOT NULL,
    "password" VARCHAR(10) NOT NULL,
    "createdAt" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "updatedAt" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS "companies"(
    "id" SERIAL PRIMARY KEY NOT NULL,
    "name" VARCHAR(40) NOT NULL,
    "address" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "updatedAt" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS "job_applications"(
    "userId" INTEGER NOT NULL REFERENCES "users"("id"),
    "jobId" INTEGER NOT NULL REFERENCES "jobs"("id"),
    "createdAt" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "updatedAt" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);
CREATE TABLE IF NOT EXISTS"jobs"(
    "id" SERIAL PRIMARY KEY NOT NULL,
    "title" VARCHAR(40) NOT NULL,
    "description" VARCHAR(255) NOT NULL,
    "companyId" INTEGER NOT NULL REFERENCES "companies"("id"),
    "createdAt" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "updatedAt" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS "courses"(
    "id" SERIAL PRIMARY KEY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "instituteName" VARCHAR(255) NOT NULL,
    "instituteLocation" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "updatedAt" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

